abstract final class RouteNames {
  static const splash = '/';
  static const onboarding = '/onboarding';
  static const login = '/login';
  static const register = '/register';
  static const verifyEmail = '/verify-email';
  static const home = '/home';
  static const marketplace = '/marketplace';
  static const associations = '/associations';
  static const services = '/services';
  static const account = '/account';
  static const news = '/news';
  static const newsArticleDetail = '/news/article';
  static const video = '/video';
  static const campus = '/campus';
  static const ppp = '/ppp';
  static const pppDetail = '/ppp/:id';
  static const pppDirectory = '/ppp/:id/directory';
  static const pppRegister = '/ppp/:id/register';
  static const jobs = '/jobs';

  // — Association sub-screens
  static const associationLogin = '/association/:id/login';
  static const associationDashboard = '/association/:id';
  static const associationDeals = '/association/:id/deals';
  static const associationDealCreate = '/association/:id/deals/create';
  static const associationDemandCreate = '/association/:id/deals/demand';
  static const associationLastMinCreate = '/association/:id/deals/lastmin';
  static const associationCirculars = '/association/:id/circulars';
  static const associationCircularDetail = '/association/:id/circulars/:cid';
  static const associationUpdates = '/association/:id/updates';
  static const associationDirectory = '/association/:id/directory';
  static const associationJobs = '/association/:id/jobs';
  static const associationJobCreate = '/association/:id/jobs/post';
  static const associationJobApplicants = '/association/:id/jobs/applicants';
  static const associationChat = '/association/:id/chat';
  static const associationChatThread = '/association/:id/chat/:chatId';
  static const associationCabs = '/association/:id/cabs';
  static const associationAdminCabs = '/association/:id/admin-cabs';
  static const advisoryBoard = '/advisory-board';
  static const destinationSpecialist = '/destination-specialist';
  static const skillDevelopment = '/skill-development';
  static const dealDetail = '/deal-detail';
  static const dealEnquiry = '/deal-enquiry';
  static const hotelDetail = '/marketplace/hotel-detail';
  static const villaSearch = '/marketplace/villa';
  static const villaDetail = '/marketplace/villa-detail';
  static const arosaResults = '/marketplace/arosa-results';

  // — Insurance & Visa
  static const insurance = '/services/insurance';
  static const insuranceConfirmation = '/services/insurance/confirmation';
  static const visa = '/services/visa';
  static const visaConfirmation = '/services/visa/confirmation';
}
