abstract final class RouteNames {
  static const splash = '/';
  static const onboarding = '/onboarding';
  static const login = '/login';
  static const register = '/register';
  static const verifyEmail = '/verify-email';
  static const home = '/home';
  static const marketplace = '/marketplace';
  static const associations = '/associations';
  static const services = '/services';
  static const account = '/account';
  static const news = '/news';
  static const video = '/video';
  static const campus = '/campus';
  static const ppp = '/ppp';
  static const jobs = '/jobs';
  static const dealDetail = '/deal-detail';
  static const dealEnquiry = '/deal-enquiry';
  static const hotelDetail = '/marketplace/hotel-detail';
  static const villaSearch = '/marketplace/villa';
  static const villaDetail = '/marketplace/villa-detail';
  static const arosaResults = '/marketplace/arosa-results';
}
